export const SENDING_REQUEST = 'SENDING_REQUEST';

export const LOGIN_ATTEMPT = 'LOGIN_ATTEMPT';
export const LOGIN_SUCCEEDED = 'LOGIN_SUCCEEDED';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const SET_LOGOUT = 'LOGOUT';
export const UNAUTHORIZED_LOGIN = 'UNAUTHORIZED_LOGIN';

export const CREATE_RULESET = 'CREATE_RULESET';
export const CREATE_RULESET_DONE = 'CREATE_RULESET_DONE';

export const EDIT_RULESET = 'EDIT_RULESET';
export const EDIT_RULESET_DONE = 'EDIT_RULESET_DONE';

export const CREATE_BILLPAY_ATTEMPT = 'CREATE_BILLPAY_ATTEMPT';
export const CREATE_BILLPAY_DONE = 'CREATE_BILLPAY_DONE';

export const CREATE_MERCHANT_RULESET_ATTEMPT = 'CREATE_MERCHANT_RULESET_ATTEMPT';
export const CREATE_MERCHANT_RULESET_DONE = 'CREATE_MERCHANT_RULESET_DONE';

export const CREATE_SETTLEMENT = 'CREATE_SETTLEMENT';
export const CREATE_SETTLEMENT_DONE = 'CREATE_SETTLEMENT_DONE';


// Create Tax rulesets

export const CREATE_TAX_RULESETS = 'CREATE_TAX_RULESETS';
export const CREATE_TAX_RULESETS_DONE = 'CREATE_TAX_RULESETS_DONE'

// export const LIST_TAX_RULESETS = 'LIST_TAX_RULESETS';
// export const LIST_TAX_RULESETS_DONE = 'LIST_TAX_RULESETS_DONE';

export const SHOW_TAX_RULE = "SHOW_TAX_RULE";
export const SHOW_TAX_RULE_DONE = "SHOW_TAX_RULE_DONE"

export const EDIT_TAX_RULE = 'EDIT_TAX_RULE';
export const EDIT_TAX_RULE_DONE = 'EDIT_TAX_RULE_DONE';

export const LIST_TAX_RULES = 'LIST_TAX_RULES';
export const LIST_TAX_RULES_DONE = 'LIST_TAX_RULES_DONE';


export const CREATE_INVOICE = 'CREATE_INVOICE';
export const CREATE_INVOICE_DONE = 'CREATE_INVOICE_DONE';

export const CREATE_DISBURSEMENT = 'CREATE_DISBURSEMENT';
export const CREATE_DISBURSEMENT_DONE = 'CREATE_DISBURSEMENT_DONE';

export const EDIT_SETTLEMENT = 'EDIT_SETTLEMENT';
export const EDIT_SETTLEMENT_DONE = 'EDIT_SETTLEMENT_DONE';

export const ADD_FILTER = 'ADD_FILTER';
export const REMOVE_FILTER = 'REMOVE_FILTER';
export const CHANGE_FILTER = 'CHANGE_FILTER';
export const CHANGE_FILTER_NAME = 'CHANGE_FILTER_NAME';

export const ADD_RULE = 'ADD_RULE';
export const CHANGE_RULE = 'CHANGE_RULE';
export const REMOVE_RULE = 'REMOVE_RULE';

export const MULTI_FIND = 'MULTI_FIND';
export const MULTI_FIND_INPUT = 'MULTI_FIND_INPUT';
export const MULTI_FIND_DONE = 'MULTI_FIND_DONE';
export const LOCK_MULTI_FIND = 'LOCK_MULTI_FIND';
export const MULTI_FIND_FAILED = 'MULTI_FIND_FAILED';
export const MULTI_FIND_CANCELLED = 'MULTI_FIND_CANCELLED';
export const EDIT_LOCK = 'EDIT_LOCK';
export const MULTI_FIND_CLEAR = 'MULTI_FIND_CLEAR';

export const MERCHANT_SEARCH = 'MERCHANT_SEARCH';
export const MERCHANT_SEARCH_DONE = 'MERCHANT_SEARCH_DONE';
export const LOCK_MERCHANT_SEARCH = 'LOCK_MERCHANT_SEARCH';
export const MERCHANT_SEARCH_FAILED = 'MERCHANT_SEARCH_FAILED';
export const MERCHANT_SEARCH_CANCELLED = 'MERCHANT_SEARCH_CANCELLED';

export const EVENT_TYPES = "EVENT_TYPES";
export const EVENT_TYPES_DONE = "EVENT_TYPES_DONE";

export const SERVICE_TYPES = "SERVICE_TYPES";
export const SERVICE_TYPES_DONE = "SERVICE_TYPES_DONE";

export const SEARCH_LIST = 'SEARCH_LIST';
export const SEARCH_RULESET_DONE = 'SEARCH_RULESET_DONE';
export const SEARCH_MERCHANT_DONE = 'SEARCH_MERCHANT_DONE';
export const SEARCH_INTERCHANGE_DONE = 'SEARCH_INTERCHANGE_DONE';
export const SEARCH_ACCOUNT_DONE = 'SEARCH_ACCOUNT_DONE';
export const SEARCH_INTERNAL_FUND_TRANSFER_DONE = 'SEARCH_INTERNAL_FUND_TRANSFER_DONE';
export const SEARCH_SETTLEMENT_DONE = 'SEARCH_SETTLEMENT_DONE';
export const SEARCH_TAX_RULE_DONE = 'SEARCH_TAX_RULE_DONE';

export const LIST_RULESETS = 'LIST_RULESETS';
export const LIST_RULESETS_DONE = 'LIST_RULESETS_DONE';

export const SHOW_RULESET = 'SHOW_RULESET';
export const SHOW_RULESET_DONE = 'SHOW_RULESETS_DONE';

export const SHOW_ON_DEMAND = 'SHOW_ON_DEMAND';
export const SHOW_ON_DEMAND_DONE = 'SHOW_ON_DEMAND_DONE';

export const CREATE_MERCHANT_ATTEMPT = 'CREATE_MERCHANT_ATTEMPT';
export const CREATE_MERCHANT_DONE = 'CREATE_MERCHANT_DONE';

export const EDIT_MERCHANT_ATTEMPT = 'EDIT_MERCHANT_ATTEMPT';
export const EDIT_MERCHANT_DONE = 'EDIT_MERCHANT_DONE';

export const LIST_MERCHANTS = 'LIST_MERCHANTS';
export const LIST_MERCHANTS_DONE = 'LIST_MERCHANTS_DONE';

export const SHOW_MERCHANT = 'SHOW_MERCHANT';
export const SHOW_MERCHANT_DONE = 'SHOW_MERCHANT_DONE';

export const ADDRESS_VERIFY_ATTEMPT = 'ADDRESS_VERIFY_ATTEMPT';
export const ADDRESS_VERIFY_DONE = 'ADDRESS_VERIFY_DONE';

export const CLEAR_TRANSACTIONAL_MESSAGES = 'CLEAR_TRANSACTIONAL_MESSAGES';

export const LIST_INTERCHANGES = 'LIST_INTERCHANGES';
export const LIST_INTERCHANGES_DONE = 'LIST_INTERCHANGES_DONE';

export const LIST_TAX_ACCOUNTS = 'LIST_TAX_ACCOUNTS';
export const LIST_TAX_ACCOUNTS_DONE = 'LIST_TAX_ACCOUNTS_DONE';

export const LIST_TAXES = 'LIST_TAXES';
export const LIST_TAXES_DONE = 'LIST_TAXES_DONE';

export const LIST_CESSES = 'LIST_CESSES';
export const LIST_CESSES_DONE = 'LIST_CESSES_DONE';

export const CREATE_ACCOUNT_ATTEMPT = 'CREATE_ACCOUNT_ATTEMPT';
export const CREATE_ACCOUNT_DONE = 'CREATE_ACCOUNT_DONE';

export const CREATE_INTERNAL_FUND_TRANSFER_ATTEMPT = 'CREATE_INTERNAL_FUND_TRANSFER_ATTEMPT';
export const CREATE_INTERNAL_FUND_TRANSFER_DONE = 'CREATE_INTERNAL_FUND_TRANSFER_DONE';

export const EDIT_ACCOUNT_ATTEMPT = 'EDIT_ACCOUNT_ATTEMPT';
export const EDIT_ACCOUNT_DONE = 'EDIT_ACCOUNT_DONE';

export const LIST_ACCOUNTS = 'LIST_ACCOUNTS';
export const LIST_ACCOUNTS_DONE = 'LIST_ACCOUNTS_DONE';

export const LIST_INTERNAL_FUND_TRANSFERS = 'LIST_INTERNAL_FUND_TRANSFERS';
export const LIST_INTERNAL_FUND_TRANSFERS_DONE = 'LIST_INTERNAL_FUND_TRANSFERS_DONE';

export const LIST_SETTLEMENTS = 'LIST_SETTLEMENTS';
export const LIST_SETTLEMENTS_DONE = 'LIST_SETTLEMENTS_DONE';

export const SHOW_ACCOUNT = 'SHOW_ACCOUNT';
export const SHOW_ACCOUNT_DONE = 'SHOW_ACCOUNT_DONE';

export const SHOW_INTERNAL_FUND_TRANSFER = 'SHOW_INTERNAL_FUND_TRANSFER';
export const SHOW_INTERNAL_FUND_TRANSFER_DONE = 'SHOW_INTERNAL_FUND_TRANSFER_DONE';

export const SHOW_SETTLEMENT = 'SHOW_SETTLEMENT';
export const SHOW_SETTLEMENT_DONE = 'SHOW_SETTLEMENT_DONE';

export const SHOW_INVOICE = 'SHOW_INVOICE';
export const SHOW_INVOICE_DONE = 'SHOW_INVOICE_DONE';

export const SHOW_DISBURSEMENT = 'SHOW_DISBURSEMENT';
export const SHOW_DISBURSEMENT_DONE = 'SHOW_DISBURSEMENT_DONE';

export const SHOW_INTERCHANGE = 'SHOW_INTERCHANGE';
export const SHOW_INTERCHANGE_DONE = 'SHOW_INTERCHANGE_DONE';

export const CREATE_INTERCHANGE_ATTEMPT = 'CREATE_INTERCHANGE_ATTEMPT';
export const CREATE_INTERCHANGE_DONE = 'CREATE_INTERCHANGE_DONE';

export const EDIT_INTERCHANGE_ATTEMPT = 'EDIT_INTERCHANGE_ATTEMPT';
export const EDIT_INTERCHANGE_DONE = 'EDIT_INTERCHANGE_DONE';

export const LIST_REPORT_TYPES = 'LIST_REPORT_TYPES';
export const LIST_REPORT_TYPES_DONE = 'LIST_REPORT_TYPES_DONE';

export const CREATE_REPORT_ATTEMPT = 'CREATE_REPORT_ATTEMPT';
export const CREATE_REPORT_DONE = 'CREATE_REPORT_DONE';

export const SHOW_TRANSACTION_STATUS = 'SHOW_TRANSACTION_STATUS';
export const SHOW_TRANSACTION_STATUS_DONE = 'SHOW_TRANSACTION_STATUS_DONE';
export const CLEAR_STATE = 'CLEAR_STATE';
export const CHANGE_TRANSACTION_STATUS = 'CHANGE_TRANSACTION_STATUS';
export const CHANGE_TRANSACTION_STATUS_DONE = 'CHANGE_TRANSACTION_STATUS_DONE';

export const APPROVE_ATTEMPT = 'APPROVE_ATTEMPT';
export const APPROVE_RATECARD_ATTEMPT = 'APPROVE_RATECARD_ATTEMPT';
export const APPROVE_DONE = 'APPROVE_DONE';
export const APPROVE_RATECARD_DONE = 'APPROVE_RATECARD_DONE';

export const ACTIVATE_ATTEMPT = 'ACTIVATE_ATTEMPT';
export const ACTIVATE_RATECARD_ATTEMPT = 'ACTIVATE_RATECARD_ATTEMPT';
export const ACTIVATE_DONE = 'ACTIVATE_DONE';
export const ACTIVATE_RATECARD_DONE = 'ACTIVATE_RATECARD_DONE';

export const DEACTIVATE_ATTEMPT = 'DEACTIVATE_ATTEMPT';
export const DEACTIVATE_RATECARD_ATTEMPT = 'DEACTIVATE_RATECARD_ATTEMPT';
export const DEACTIVATE_DONE = 'DEACTIVATE_DONE';
export const DEACTIVATE_RATECARD_DONE = 'DEACTIVATE_RATECARD_DONE';

export const SOMETHING_WENT_WRONG = 'SOMETHING_WENT_WRONG';

export const INVALID_FORM = 'INVALID_FORM';

export const MERCHANT_SETTLEMENT_STATUS = "MERCHANT_SETTLEMENT_STATUS";
export const LIST_MERCHANT_SETTLEMENTS_DONE = "LIST_MERCHANT_SETTLEMENTS_DONE";

export const LOOKUP_UTR = 'LOOKUP_UTR';
export const LOOKUP_UTR_DONE = 'LOOKUP_UTR_DONE';

export const REPLAY_DISBURSEMENT = 'REPLAY_DISBURSEMENT';
export const REPLAY_DISBURSEMENT_DONE = 'REPLAY_DISBURSEMENT_DONE';

export const CREATE_PG = "CREATE_PG";
export const CREATE_PG_DONE = "CREATE_PG_DONE";

export const EDIT_PG = "EDIT_PG";
export const EDIT_PG_DONE = "EDIT_PG_DONE";

export const SHOW_PG = 'SHOW_PG';
export const SHOW_PG_DONE = 'SHOW_PG_DONE';

export const LIST_PGS = 'LIST_PGS';
export const LIST_PGS_DONE = 'LIST_PGS_DONE';

export const SHOW_RATECARDS = 'SHOW_RATECARDS';
export const SHOW_RATECARDS_DONE = 'SHOW_RATECARDS_DONE';

export const EDIT_RATECARD = 'EDIT_RATECARD';
export const EDIT_RATECARD_DONE = 'EDIT_RATECARD_DONE';

export const PENDING_SETTLEMENT_AMOUNT = "PENDING_SETTLEMENT_AMOUNT";
export const PENDING_SETTLEMENT_AMOUNT_DONE = "PENDING_SETTLEMENT_AMOUNT_DONE";

export const INVOICE_RECOVERY = "INVOICE_RECOVERY";
export const INVOICE_RECOVERY_DONE = "INVOICE_RECOVERY_DONE";

export const TOA_CLOSE = "TOA_CLOSE";
export const TOA_CLOSE_DONE = "TOA_CLOSE_DONE";

export const CREATE_PG_RATE_CARD = "CREATE_PG_RATE_CARD";
export const CREATE_PG_RATE_CARD_DONE = "CREATE_PG_RATE_CARD_DONE";
export const LIST_PG_RATE_CARDS = "LIST_PG_RATE_CARDS";
export const LIST_PG_RATE_CARDS_DONE = "LIST_PG_RATE_CARDS_DONE";
export const SEARCH_PG_RATE_CARD_DONE = "SEARCH_PG_RATE_CARD_DONE";

export const LIST_PG_RATE_CARD_MIDS = "LIST_PG_RATE_CARD_MIDS";
export const LIST_PG_RATE_CARD_MIDS_DONE = "LIST_PG_RATE_CARD_MIDS_DONE";

export const CREATE_PG_MID = "CREATE_PG_MID";
export const CREATE_PG_MID_DONE = "CREATE_PG_MID_DONE";
export const LIST_PG_MIDS = "LIST_PG_MIDS";
export const LIST_PG_MIDS_DONE = "LIST_PG_MIDS_DONE";
export const SEARCH_PG_RATE_CARDS_DONE = "SEARCH_PG_RATE_CARDS_DONE";
export const SEARCH_PG_MID_DONE = "SEARCH_PG_MID_DONE";
export const SHOW_PG_MID = 'SHOW_PG_MID';
export const SHOW_PG_MID_DONE = 'SHOW_PG_MID_DONE';

export const CREATE_RATECARD_TEMPLATE = 'CREATE_RATECARD_TEMPLATE';
export const CREATE_RATECARD_TEMPLATE_DONE = 'CREATE_RATECARD_TEMPLATE_DONE';
export const LIST_RATE_CARD_TEMPLATE = 'LIST_RATE_CARD_TEMPLATE';
export const LIST_RATE_CARD_TEMPLATE_DONE = 'LIST_RATE_CARD_TEMPLATE_DONE';
export const SHOW_RATE_CARD_TEMPLATE = 'SHOW_RATE_CARD_TEMPLATE';
export const SHOW_RATE_CARD_TEMPLATE_DONE = 'SHOW_RATE_CARD_TEMPLATE_DONE';

export const CREATE_COMPOSED_MERCHANT_ATTEMPT = 'CREATE_COMPOSED_MERCHANT_ATTEMPT';
export const CREATE_COMPOSED_MERCHANT_DONE = 'CREATE_COMPOSED_MERCHANT_DONE';

export const CREATE_COMPOSED_PG_ATTEMPT = 'CREATE_COMPOSED_PG_ATTEMPT';
export const CREATE_COMPOSED_PG_DONE = 'CREATE_COMPOSED_PG_DONE';

export const CREATE_COMPOSED_AGGREGATOR_ATTEMPT = 'CREATE_COMPOSED_AGGREGATOR_ATTEMPT';
export const CREATE_COMPOSED_AGGREGATOR_DONE = 'CREATE_COMPOSED_AGGREGATOR_CREATE_COMPOSED_AGGREGATOR_DONE';

export const GET_AGGREGATOR_SERVICE_TYPE = 'GET_AGGREGATOR_SERVICE_TYPE';
export const GET_AGGREGATOR_SERVICE_TYPE_DONE = 'GET_AGGREGATOR_SERVICE_TYPE_DONE';

export const GET_SAC_CODE = 'GET_SAC_CODE';
export const GET_SAC_CODE_DONE = 'GET_SAC_CODE_DONE'

export const RULESET_RATE_CARD_TEMPLATE_MAPPING_ATTEMPT = 'RULESET_RATE_CARD_TEMPLATE_MAPPING_ATTEMPT';
export const ACTIVATE_RULESET_RATE_CARD_TEMPLATE_MAPPING_ATTEMPT = 'ACTIVATE_RULESET_RATE_CARD_TEMPLATE_MAPPING_ATTEMPT';

export const CREATE_AGGREGATOR_SERVICE_TYPE = 'CREATE_AGGREGATOR_SERVICE_TYPE';
export const CREATE_AGGREGATOR_SERVICE_TYPE_DONE = 'CREATE_AGGREGATOR_SERVICE_TYPE_DONE';

export const LIST_AGGREGATE_TYPES='LIST_AGGREGATE_TYPES';
export const LIST_AGGREGATE_TYPES_DONE='LIST_AGGREGATE_TYPES_DONE';

export const LOCATION_CHANGE = '@@router/LOCATION_CHANGE';


export const CREATE_COMPOSED_CAMPAIGN_ATTEMPT = 'CREATE_COMPOSED_CAMPAIGN_ATTEMPT';
export const CREATE_COMPOSED_CAMPAIGN_DONE = 'CREATE_COMPOSED_CAMPAIGN_DONE';