export const FIXED_COMMISSION_RULE = "FIXED_COMMISSION_RULE";
export const FIXED_INTERCHANGE_FEE_RULE = "FIXED_INTERCHANGE_FEE_RULE";
export const FIXED_RATE_COMMISSION_RULE = "FIXED_RATE_COMMISSION_RULE";
export const FIXED_RATE_INTERCHANGE_FEE_RULE = "FIXED_RATE_INTERCHANGE_FEE_RULE";
export const SLABBED_FIXED_COMMISSION_RULE = "SLABBED_FIXED_COMMISSION_RULE";
export const SLABBED_FIXED_INTERCHANGE_FEE_RULE = "SLABBED_FIXED_INTERCHANGE_FEE_RULE";
export const SLABBED_FIXED_RATE_COMMISSION_RULE = "SLABBED_FIXED_RATE_COMMISSION_RULE";
export const SLABBED_FIXED_RATE_INTERCHANGE_FEE_RULE = "SLABBED_FIXED_RATE_INTERCHANGE_FEE_RULE";
export const ACCOUNT_ENTRY_RULE = "ACCOUNT_ENTRY_RULE";

//For rate card template rulesetss
export const BASIC_RATE_CARD_RULE = "BASIC_RATE_CARD_RULE";
export const COUNT_BASED_RATE_CARD_RULE = "COUNT_BASED_RATE_CARD_RULE";

export const PRE_CALCULATED_RATE_CARD_RULE = "PRE_CALCULATED_RATE_CARD_RULE";

//For Composed Campaign and merchant ruleset
export const COMPOSED_MERCHANT_RULE_SET = "COMPOSED_MERCHANT_RULE_SET";
export const COMPOSED_CAMPAIGN_RULE_SET = "COMPOSED_CAMPAIGN_RULE_SET";
